### PR TITLE
added italian language

### PR DESCRIPTION
**Pull request by koreldan**
I've compiled and tested locally the coriolis.io to check translation... i hope i didn't miss anything.

### CODE REVIEW

**Comment by cmmcleod** [comment]
Very nice, thanks!

**Comment by koreldan** [comment]
you are welcome ;)

when it will be published ? :)

**Comment by cmmcleod** [comment]
In a day or two. Just finishing up some other things for the next release.

It will be release in 1.7.0

I did notice there were a few translations missing. I'm using OneSky to manage translations. You can see the missing translations here:

https://coriolis.oneskyapp.com/collaboration/translate/project/project/96817/language-from/1/language/10/#/filter/not-yet-translated/

It's fine that certain things are not translated, e.g. 'Advanced Discovery Scanner', but other things probably should be, e.g. 'backup', etc.

**Comment by koreldan** [comment]
Done.

**Pull request merged**
