### PR TITLE
Priority alpha 2.0

### PR DESCRIPTION
**Pull request by PanzerKadaver**
Priority for #14
See #41 for old pull request (alpha 1.0)

### CODE REVIEW

**Comment by PanzerKadaver** [comment]
So I integrate all of your suggestions, keep the hardpoint toggle, add priority summary (power usage in each priority + cumulative priority) and last but least make the code more clean.

Feel free to play with my test build (which is require a deep power management) :
/outfit/federal_dropship/06A6A5A5A6A4A4C160t0t0t2m000404044f0404321q6v24?bn=Iron%20Spark

**Comment by cmmcleod** [comment]
Merge the with the latest master here https://github.com/cmmcleod/coriolis/tree/Toxicat-priority-alpha2

Taking a look now :)

**Comment by PanzerKadaver** [comment]
> This pull request contains merge conflicts

I'm curious, which one ?

**Comment by cmmcleod** [comment]
I ended up refactoring an awful lot of code for performance improvement in general and copied msot of your priority management stuff. It is in master now. The commit is 1367418fb2b91ab281f3b5a5145526ec57b92a8d.

**Comment by cmmcleod** [comment]
Thanks for all of this work! At lot of it has been incorporated into master now :) Closing since the feature is now in master.

**Comment by PanzerKadaver** [comment]
Woah ! You make huge modifications ! Sadly I can't build on my office computer. But, as far I can see, my commit wasn't added (/me little sad).

**Comment by cmmcleod** [comment]
I know, I'm sorry! :( I ended up changing a lot of stuff unrelated to your commit. But it did inspire me and I used your code a a basis.

What builds problems are you having?

**Comment by cmmcleod** [comment]
make sure you run `npm install` and `bower install` before running any gulp task

**Comment by PanzerKadaver** [comment]
Don't worry, the most important is that the project move forward :)

And for the build, is not about problem ^^ It's about that I'm not allowed to put irrelevant code on my office computer. I'll have to wait lunch time to pull master on my personal laptop.

**Pull request closed without merging**
