### PR TITLE
Additional auto-fill for SCB and other weapons

### PR DESCRIPTION
**Pull request by sf302**
Building off of df7ef0fbdb286110d2699ca65c4bf4f4da53b5bb to add SCB internal fill. Handles Orca special case and avoids overwriting generator as well as disabling "excess" cells to avoid wasting charges.

Also filled out the other weapons for hardpoint auto-fill. Tweaked behavior to mount largest available so things like rail guns and multi-cannons behave in line with expectations.

### CODE REVIEW

**Comment by sf302** [comment]
Unsure how you want to handle hardpoints that can't handle the smallest class available (PA). Current behavior leaves that slot alone, but it might be preferable to vacate that slot.

Conversely, if it's indeed better to keep that slot as-is, it might be worthwhile to modify the internal auto-fills to avoid clobbering existing modules.

**Comment by cmmcleod** [comment]
The purpose of these quick-fit menus is to help users fill slots with typical/common setups.

Plasma accelerators aren't that common, so I'd exclude them.

In fact I deliberately only added Pulse, Beam and Burst lasers. 

Multi-cannons, Missile Rack may make sense too, but not every possible weapon. Thoughts?

**Comment by sf302** [comment]
Sounds fine to me to leave it at just cannons and multi-cannons added, then.

Missiles are pretty lousy against shields, so "nobody" should be filling out all their hardpoints with missiles.

**Comment by cmmcleod** [comment]
:+1:

**Pull request merged**
